[tool.mypy]
python_version = "3.10"
files = [".config/ignis"]
exclude = ["venv"]
disable_error_code = [
    "no-redef",  # allow variable redefinition (needed for GObject.Property decorator)
    "method-assign"  # also needed for GObject.Property,
]
mypy_path = ["stubs"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["gi.repository.*"]
disable_error_code = ["assignment"]

[[tool.mypy.overrides]]
module = ["materialyoucolor.*"]
disable_error_code = ["import-untyped"]